apiVersion: v1
kind: ConfigMap
metadata:
  name: shopverse-config
  labels:
    app: shopverse
data:
  DB_HOST: shopverse-mysql
  DB_PORT: "3306"
  DB_NAME: {{ .Values.mysql.database | quote }}
  DB_USER: {{ .Values.mysql.user | quote }}
  FRONTEND_ORIGIN: "*"
