apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  labels:
    app: shopverse
    component: frontend
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: shopverse
    component: frontend
