apiVersion: v1
kind: Service
metadata:
  name: shopverse-mysql
  labels:
    app: shopverse
    component: mysql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: shopverse
    component: mysql
