apiVersion: v1
kind: Secret
metadata:
  name: shopverse-secret
  labels:
    app: shopverse
type: Opaque
data:
  DB_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
